# This is a basic workflow that is manually triggered

name: Build

on:
  push:
    branches: ["release/*"]

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Manul build"

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
        os: [windows-latest, macos-latest, macos-latest-xlarge]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Echo Current Path
        run: echo ${{ github.workspace }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run tauri build

      - name: Download
        uses: actions/upload-artifact@v3
        with:
          name: Build.dmg
          path: src-tauri/target/release/bundle/dmg/blackhole_0.0.0_aarch64.dmg
